### ISSUE TITLE
Do not work with tag "space"

### ISSUE THREAD

**Issue by Zatalyz** [geekitude/dokuwiki-plugin-tagalerts#1]
Hello,

And first, thanks for your plugin, it is nice :)

Plugin Tag accepts complex tag with "space". If I want to have a tag like "some word", I write the syntax "{{tag>some_word}}". With Tagalerts, it work to declare it on administration panel, but not in the customization of headings. In "conf/tagalerts.conf", if I declare `some_word My description example`, the custom message is not displayed (it remains the default). 

Screenshot of result on page:
![tagalerts_page](https://user-images.githubusercontent.com/10725489/52423859-37a08200-2af9-11e9-9da5-34d9b94df778.png)

Screenshot of my config file :
![tagalerts_conf](https://user-images.githubusercontent.com/10725489/52423847-33746480-2af9-11e9-856d-d9f1c1a80930.png)

My wiki is on Release 2018-04-22b "Greebo" and plugin is update.

**Comment by geekitude** [comment]
Hi

I will try to look at that within a few days.
Can you send me a screenshot of your Tagalerts settings ?
This should help me to understand thé problem.

**Comment by Zatalyz** [comment]
![tagalerts_admin](https://user-images.githubusercontent.com/10725489/52489981-fcb75080-2bc3-11e9-81cd-d2b9f8b9c64a.png)

**Comment by Zatalyz** [comment]
It work, thanks a lot \o/
